/**
 * Campaign Routes
 *
 * Routes for managing marketing campaigns in legal CRM
 * Auth handled globally by authenticatedApi middleware
 *
 * Base route: /api/campaigns
 */

const express = require('express');
const router = express.Router();
const campaignController = require('../controllers/campaign.controller');

// ============================================
// CAMPAIGN CRUD OPERATIONS
// ============================================

/**
 * @route   POST /api/campaigns
 * @desc    Create a new campaign
 * @access  Private
 */
router.post('/', campaignController.createCampaign);

/**
 * @route   GET /api/campaigns
 * @desc    Get all campaigns with filters
 * @query   search, status, type, ownerId, teamId, page, limit
 * @access  Private
 */
router.get('/', campaignController.getCampaigns);

/**
 * @route   GET /api/campaigns/:id
 * @desc    Get single campaign by ID
 * @access  Private
 */
router.get('/:id', campaignController.getCampaignById);

/**
 * @route   PUT /api/campaigns/:id
 * @desc    Update campaign
 * @access  Private
 */
router.put('/:id', campaignController.updateCampaign);

/**
 * @route   DELETE /api/campaigns/:id
 * @desc    Delete campaign
 * @access  Private
 */
router.delete('/:id', campaignController.deleteCampaign);

// ============================================
// CAMPAIGN STATUS OPERATIONS
// ============================================

/**
 * @route   POST /api/campaigns/:id/launch
 * @desc    Launch a campaign (set status to active)
 * @access  Private
 */
router.post('/:id/launch', campaignController.launchCampaign);

/**
 * @route   POST /api/campaigns/:id/pause
 * @desc    Pause an active campaign
 * @access  Private
 */
router.post('/:id/pause', campaignController.pauseCampaign);

/**
 * @route   POST /api/campaigns/:id/resume
 * @desc    Resume a paused campaign
 * @access  Private
 */
router.post('/:id/resume', campaignController.resumeCampaign);

/**
 * @route   POST /api/campaigns/:id/complete
 * @desc    Mark campaign as completed
 * @access  Private
 */
router.post('/:id/complete', campaignController.completeCampaign);

// ============================================
// CAMPAIGN ANALYTICS & DATA
// ============================================

/**
 * @route   GET /api/campaigns/:id/stats
 * @desc    Get campaign statistics and ROI
 * @access  Private
 */
router.get('/:id/stats', campaignController.getCampaignStats);

/**
 * @route   GET /api/campaigns/:id/leads
 * @desc    Get leads generated by campaign
 * @query   page, limit
 * @access  Private
 */
router.get('/:id/leads', campaignController.getCampaignLeads);

// ============================================
// CAMPAIGN UTILITIES
// ============================================

/**
 * @route   POST /api/campaigns/:id/duplicate
 * @desc    Duplicate an existing campaign
 * @access  Private
 */
router.post('/:id/duplicate', campaignController.duplicateCampaign);

module.exports = router;
